services:
  db:
    container_name: my-postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: flaskapp
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
    - ~/Programs/postgresql/data:/var/lib/postgresql/data
 
