version: '3.7'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: metastore
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hivepassword
    ports:
      - "5433:5432"

  hive-metastore:
    image: apache/hive:3.1.3
    environment:
      SERVICE_NAME: metastore
      HIVE_METASTORE_DB_TYPE: postgres
      HIVE_METASTORE_URI: thrift://0.0.0.0:9083
      DB_URL: jdbc:postgresql://postgres:5433/metastore
      DB_USER: hive
      DB_PASSWORD: hivepassword
    depends_on:
      - postgres
    ports:
      - "9083:9083"

  trino:
    image: trinodb/trino:latest
    ports:
      - "10006:8080"
    volumes:
      - ${TRINO_PATH}/etc:/etc/trino
      - ${TRINO_PATH}/warehouse:/warehouse
    depends_on:
      - hive-metastore
