version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio-server
    ports:
      - "9000:9000"  # API access
      - "9001:9001"  # MinIO Console
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: 1234qwer
    volumes:
      - minio_data:/data  # Persistent storage volume
    command: server /data --console-address ":9001"
volumes:
  minio_data:
    driver: local
